// Mocks generated by Mockito 5.4.4 from annotations
// in marvel_app/test/services/marvel_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i4;
import 'package:marvel_app/api/marvel_api.dart' as _i5;
import 'package:marvel_app/data/response/character_response.dart' as _i6;
import 'package:marvel_app/domain/entities/common.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCancellable_0<T> extends _i1.SmartFake
    implements _i2.Cancellable<T> {
  _FakeCancellable_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCancelToken_2 extends _i1.SmartFake implements _i4.CancelToken {
  _FakeCancelToken_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MarvelApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarvelApi extends _i1.Mock implements _i5.MarvelApi {
  MockMarvelApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Cancellable<_i6.MarvelApiResponse> getCharacters() => (super.noSuchMethod(
        Invocation.method(
          #getCharacters,
          [],
        ),
        returnValue: _FakeCancellable_0<_i6.MarvelApiResponse>(
          this,
          Invocation.method(
            #getCharacters,
            [],
          ),
        ),
      ) as _i2.Cancellable<_i6.MarvelApiResponse>);
}

/// A class which mocks [Cancellable].
///
/// See the documentation for Mockito's code generation for more information.
class MockCancellable<T> extends _i1.Mock implements _i2.Cancellable<T> {
  MockCancellable() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<T> get call => (super.noSuchMethod(
        Invocation.getter(#call),
        returnValue: _i7.ifNotNull(
              _i7.dummyValueOrNull<T>(
                this,
                Invocation.getter(#call),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.getter(#call),
            ),
      ) as _i3.Future<T>);

  @override
  _i4.CancelToken get token => (super.noSuchMethod(
        Invocation.getter(#token),
        returnValue: _FakeCancelToken_2(
          this,
          Invocation.getter(#token),
        ),
      ) as _i4.CancelToken);
}
